version: '3.0'

services:

  db:
    image: mysql:5.7
    container_name: fastapi-db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: fastapi
      MYSQL_ROOT_PASSWORD: 123456