version: '3.0'

services:
  lrtest-api:
    image: image
    ports:
      - 8082:8082
    volumes:
      - pyenv:/root/.pyenv
      - pipenv:/root/.cache/pipenv
      - .:/app
    command: >
      bash -cx " pyenv install --skip-existing
      && pipenv install
      && pipenv run gunicorn app.main:app"

volumes:
  pyenv:
  pipenv:
